name: CI

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Set up JDK 11
      uses: actions/setup-java@v2
      with:
        java-version: '11'
        distribution: 'adopt'

    - name: Build with Maven
      run: mvn clean verify

    - name: Upload coverage reports to Codecov
      uses: codecov/codecov-action@v3
      with:
        token: ${{ secrets.CODECOV_TOKEN }}
      # env:
      #   CODECOV_TOKEN: b023f1ca-0119-4753-a902-dc7c8e548d00
      with:
        directory: ./target/site/jacoco/ # 또는 다른 커버리지 보고서 경로
        flags: unittests # 플래그는 선택 사항
        name: codecov-umbrella # 또한 선택 사항
        fail_ci_if_error: true # 커버리지 업로드 실패 시 CI 실패로 표시